export const ProductList = [
  ["Sim", "sim"],
  ["Three Phase Meter", "3-phaseMeter"],
  ["One Phase Meter", "1-phaseMeter"],
 // ["Old Modem", "modem"],
  ["LCD Modem", "lcdModem"],
   ["Wifi Modem", "wifiModem"],
   ["Small Body DCU Plus Modem", "smallBodyDcuPlusModem"],
  // ["wavezigbeeModem", "wavezigbeeModem"],
  ["Home Display Unit", "homeDisplayunit"],
  ["DG Indicator", "DGIndicator"],
  ["IRDTRH", "DTRH"],
  ["Port DTRH", "PortDTRH"],
  ["Master DTRH", "MasterDTRH"],
  ["Wifi Dongle", "wifiDongle"],
  ["New DCU", "NewDCU"],
  ["RF-ESP-32(Merlin)", "ZigbeeRF"],
  ["Injector AVR", "InjectorAVR"],
  ["PLCC Injector", "plccInjector"],
  ["Injector Controller", "InjectorController"],
  ["Injector Meter", "injectorMeter"],
 // ["Drill/Hammer Machine", "Drill/HammerMachine"],
  ["Smart Three Phase Meter", "smart-3-phaseMeter"],
  ["Smart one Phase Meter", "smart-1-phaseMeter"],
  ["RF2-TTL", "RF2-TTL"],
  ["RF2-AB", "RF2-485"],
  ["Extension", "extensions"],
  ["Shifting Relay", "shiftingRelay"],
  ["Cat 6-Wire", "catSixWire"],
  ["CT Meter", "ctMeter"],
  ["Site Tool", "siteTool"],
  // ["ON/OFF Tool", "onOffTool"],
  // ["NO USE", "noUse"],  
  ["Sensor Itron", "sensor"],
  ["SMPS", "smps"],
  ["Tyasis Sym", "tyasisSims"],
  ["M2M Sim", "m2mSim"],
  ["Jio Sim", "jioSim"],
  ["Elmex Wire", "elmexWire"],
  ["Dye", "Dye"],
  ["LCD DCU", "lcdDcu"],
  ["Crystal Meter", "crystalMeter"],
];
