export const ProductList = [
  ["Sim", "sim"],
  ["Three Phase Meter", "3-phaseMeter"],
  ["One Phase Meter", "1-phaseMeter"],
  ["LCD Modem", "lcdModem"],
  ["Wifi Modem", "wifiModem"],
  ["Small Body DCU Plus Modem", "smallBodyDcuPlusModem"],
  ["Home Display Unit", "homeDisplayunit"],
  ["DG Indicator", "DGIndicator"],
  ["IRDTRH", "DTRH"],
  ["Port DTRH", "PortDTRH"],
  ["Master DTRH", "MasterDTRH"],
  ["Wifi Dongle", "wifiDongle"],
  ["New DCU", "NewDCU"],
  ["RF-ESP-32(Merlin)", "ZigbeeRF"],
  ["Injector AVR", "InjectorAVR"],
  ["PLCC Injector", "plccInjector"],
  ["Injector Controller", "InjectorController"],
  ["Injector Meter", "injectorMeter"],
  ["Smart Three Phase Meter", "smart-3-phaseMeter"],
  ["Smart one Phase Meter", "smart-1-phaseMeter"],
  ["RF2-TTL", "RF2-TTL"],
  ["RF2-AB", "RF2-485"],
  ["Extension", "extensions"],
  ["Shifting Relay", "shiftingRelay"],   
  ["Cat 6-Wire", "catSixWire"],
  ["CT Meter", "ctMeter"],
  ["Site Tool", "siteTool"],  
  ["Sensor Itron", "sensor"],
  ["SMPS", "smps"],
  ["Tyasis Sym", "tyasisSims"],
  ["M2M Sim", "m2mSim"],
  ["Jio Sim", "jioSim"],
  ["Elmex Wire", "elmexWire"],
  ["Dye", "Dye"],
  ["LCD DCU", "lcdDcu"],
  ["Crystal Meter", "crystalMeter"],
  ["DCU Modem", "dcuModem"],
  ["DG Modem", "dgModem"],
  ["Crystal Interphase  Port", "crystalInterphasePort"],
  // ["Crystal Interphase 3 Port", "crystalInterphase3Port"],
  // ["Crystal Interphase 4 Port" , "crystalInterphase4Port" ],
  ["Crystal Power" , "crystalPower" ],
  ["Crystal Interface PES" , "crystalInterfacePes" ],
];
